name: Keep Alive Action

on:
  schedule:
    - cron: '0 * * * *' # يعمل رأس كل ساعة
  workflow_dispatch:      # زر لتشغيله يدوياً

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a simple script
        run: echo "Server is still running!"
        
